source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               tasks/,\
               build.properties,\
               bin/
jre.compilation.profile = JavaSE-17
